from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.similarity_post_request_peak_list import SimilarityPostRequestPeakList
from openapi_server import util

from openapi_server.models.similarity_post_request_peak_list import SimilarityPostRequestPeakList  # noqa: E501

class SimilarityPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, peak_list=None):  # noqa: E501
        """SimilarityPostRequest - a model defined in OpenAPI

        :param peak_list: The peak_list of this SimilarityPostRequest.  # noqa: E501
        :type peak_list: SimilarityPostRequestPeakList
        """
        self.openapi_types = {
            'peak_list': SimilarityPostRequestPeakList
        }

        self.attribute_map = {
            'peak_list': 'peak_list'
        }

        self._peak_list = peak_list

    @classmethod
    def from_dict(cls, dikt) -> 'SimilarityPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _similarity_post_request of this SimilarityPostRequest.  # noqa: E501
        :rtype: SimilarityPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def peak_list(self) -> SimilarityPostRequestPeakList:
        """Gets the peak_list of this SimilarityPostRequest.


        :return: The peak_list of this SimilarityPostRequest.
        :rtype: SimilarityPostRequestPeakList
        """
        return self._peak_list

    @peak_list.setter
    def peak_list(self, peak_list: SimilarityPostRequestPeakList):
        """Sets the peak_list of this SimilarityPostRequest.


        :param peak_list: The peak_list of this SimilarityPostRequest.
        :type peak_list: SimilarityPostRequestPeakList
        """

        self._peak_list = peak_list
