from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SimilarityPostRequestPeakList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mz=None, intensity=None, reference_spectra_list=None):  # noqa: E501
        """SimilarityPostRequestPeakList - a model defined in OpenAPI

        :param mz: The mz of this SimilarityPostRequestPeakList.  # noqa: E501
        :type mz: List[float]
        :param intensity: The intensity of this SimilarityPostRequestPeakList.  # noqa: E501
        :type intensity: List[float]
        :param reference_spectra_list: The reference_spectra_list of this SimilarityPostRequestPeakList.  # noqa: E501
        :type reference_spectra_list: List[str]
        """
        self.openapi_types = {
            'mz': List[float],
            'intensity': List[float],
            'reference_spectra_list': List[str]
        }

        self.attribute_map = {
            'mz': 'mz',
            'intensity': 'intensity',
            'reference_spectra_list': 'reference_spectra_list'
        }

        self._mz = mz
        self._intensity = intensity
        self._reference_spectra_list = reference_spectra_list

    @classmethod
    def from_dict(cls, dikt) -> 'SimilarityPostRequestPeakList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _similarity_post_request_peak_list of this SimilarityPostRequestPeakList.  # noqa: E501
        :rtype: SimilarityPostRequestPeakList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mz(self) -> List[float]:
        """Gets the mz of this SimilarityPostRequestPeakList.

        m/z value  # noqa: E501

        :return: The mz of this SimilarityPostRequestPeakList.
        :rtype: List[float]
        """
        return self._mz

    @mz.setter
    def mz(self, mz: List[float]):
        """Sets the mz of this SimilarityPostRequestPeakList.

        m/z value  # noqa: E501

        :param mz: The mz of this SimilarityPostRequestPeakList.
        :type mz: List[float]
        """

        self._mz = mz

    @property
    def intensity(self) -> List[float]:
        """Gets the intensity of this SimilarityPostRequestPeakList.

        intensity values  # noqa: E501

        :return: The intensity of this SimilarityPostRequestPeakList.
        :rtype: List[float]
        """
        return self._intensity

    @intensity.setter
    def intensity(self, intensity: List[float]):
        """Sets the intensity of this SimilarityPostRequestPeakList.

        intensity values  # noqa: E501

        :param intensity: The intensity of this SimilarityPostRequestPeakList.
        :type intensity: List[float]
        """

        self._intensity = intensity

    @property
    def reference_spectra_list(self) -> List[str]:
        """Gets the reference_spectra_list of this SimilarityPostRequestPeakList.

        the reference spectra list, list of ACCESSION strings  # noqa: E501

        :return: The reference_spectra_list of this SimilarityPostRequestPeakList.
        :rtype: List[str]
        """
        return self._reference_spectra_list

    @reference_spectra_list.setter
    def reference_spectra_list(self, reference_spectra_list: List[str]):
        """Sets the reference_spectra_list of this SimilarityPostRequestPeakList.

        the reference spectra list, list of ACCESSION strings  # noqa: E501

        :param reference_spectra_list: The reference_spectra_list of this SimilarityPostRequestPeakList.
        :type reference_spectra_list: List[str]
        """

        self._reference_spectra_list = reference_spectra_list
